# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
- name: languages
  displayName: 'Select languages for SDK generation'
  type: object
  default:
    - 'csharp'
    - 'java'
  values:
    - 'csharp'
    - 'java'
    - 'python'
    - 'typescript'
    - 'ruby'
    - 'php'

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Validate_Spec_Stage'
  jobs:
  - job: Validate_OpenAPI_Spec
    steps:
    - script: cat openapi.json
      displayName: 'Display openapi.json Content'    
    - script: |
        # Assuming the OpenAPI spec is named 'openapi.yaml' and located at the root
        curl -X POST -H 'Content-Type: application/json' --data-binary @openapi.json https://validator.swagger.io/validator/debug
      displayName: 'Validate OpenAPI Specification'
