# File: generate-sdk-template.yml
parameters:
- name: language
  type: string
- name: generateSDK
  type: boolean
  default: false

jobs:
- job: Generate_${{ parameters.language }}
  condition: eq('${{ parameters.generateSDK }}', 'true')
  steps:
  - template: install-speakeasy-cli.yml
  - template: clone-repo.yml
    parameters:
      repoUrl: "docuTest-${{parameters.language}}-sdk-private"
      targetDirectory: "private-sdks/docuTest-${{parameters.language}}-sdk-private"
  - script: |
      cd "docusign-test-js-sdk"
      echo $(SPEAKEASY_API_KEY)
      speakeasy run
    displayName: 'Generate ${{ parameters.language }} SDK'

  - publish: ./docusign-test-js-sdk
    artifact: ${{ parameters.language }}-sdk
    displayName: 'Publish ${{ parameters.language }} SDK as artifact'

 # - publish: ./sdks/${{ parameters.language }}
