# File: generate-sdk-template.yml
parameters:
- name: language
  type: string
- name: generateSDK
  type: boolean
  default: false

jobs:
- job: Generate_${{ parameters.language }}
  condition: eq('${{ parameters.generateSDK }}', 'true')
  steps:
  - template: generate-sdk-template.yml
  - script: |
      speakeasy run
    displayName: 'Generate ${{ parameters.language }} SDK'

  - publish: ./sdks/${{ parameters.language }}
    artifact: ${{ parameters.language }}-sdk
    displayName: 'Publish ${{ parameters.language }} SDK as artifact'
